---------------------------- MODULE RustObs ----------------------------
\* GENERATED by `cargo run --example gen_model` — DO NOT EDIT.
\*
\* Observed report facts from REAL `Explorer::explore` runs over the
\* component in `examples/gen_model.rs`, which implements exactly the
\* `Step`/`Closes` transition function `ExplorerReplay.tla` hard-codes.
\* `ModelMatchesRust` compares these against counters the model computes
\* for itself. Regenerate with `scripts/check-model.sh --write`; that
\* script also fails if the committed copy has drifted.
EXTENDS Naturals

ObsCaps   == {1, 3}
ObsWorlds == {"free", "drain"}

ObsStates      == [w \in ObsWorlds |-> CASE w = "free" -> [d \in ObsCaps |-> CASE d = 1 -> 2 [] d = 3 -> 3]
                        [] w = "drain" -> [d \in ObsCaps |-> CASE d = 1 -> 1 [] d = 3 -> 1]]
ObsTransitions == [w \in ObsWorlds |-> CASE w = "free" -> [d \in ObsCaps |-> CASE d = 1 -> 2 [] d = 3 -> 6]
                        [] w = "drain" -> [d \in ObsCaps |-> CASE d = 1 -> 0 [] d = 3 -> 0]]
ObsTerminal    == [w \in ObsWorlds |-> CASE w = "free" -> [d \in ObsCaps |-> CASE d = 1 -> 1 [] d = 3 -> 3]
                        [] w = "drain" -> [d \in ObsCaps |-> CASE d = 1 -> 0 [] d = 3 -> 0]]
ObsExhausted   == [w \in ObsWorlds |-> CASE w = "free" -> [d \in ObsCaps |-> CASE d = 1 -> FALSE [] d = 3 -> TRUE]
                        [] w = "drain" -> [d \in ObsCaps |-> CASE d = 1 -> TRUE [] d = 3 -> TRUE]]
ObsDiverged    == [w \in ObsWorlds |-> CASE w = "free" -> [d \in ObsCaps |-> CASE d = 1 -> FALSE [] d = 3 -> FALSE]
                        [] w = "drain" -> [d \in ObsCaps |-> CASE d = 1 -> TRUE [] d = 3 -> TRUE]]
=======================================================================
