---------------------------- MODULE RustObs ----------------------------
\* GENERATED by `cargo run --example gen_model` — DO NOT EDIT.
\*
\* Observed report counters from a REAL `Explorer::explore` run over the
\* component in `examples/gen_model.rs`, which implements exactly the
\* `Step`/`Closes` transition function `ExplorerReplay.tla` hard-codes.
\* `ModelMatchesRust` compares these against counters the model computes
\* for itself. Regenerate with `scripts/check-model.sh --write`; that
\* script also fails if the committed copy has drifted.
EXTENDS Naturals

ObsCaps == {1, 3}
ObsStates      == [d \in ObsCaps |-> CASE d = 1 -> 2 [] d = 3 -> 3]
ObsTransitions == [d \in ObsCaps |-> CASE d = 1 -> 2 [] d = 3 -> 6]
ObsTerminal    == [d \in ObsCaps |-> CASE d = 1 -> 1 [] d = 3 -> 3]
ObsExhausted   == [d \in ObsCaps |-> CASE d = 1 -> FALSE [] d = 3 -> TRUE]
=======================================================================
