//! Generates `spec/tla/lib/RustObs.tla` — the ONLY tie between the TLA+ model and
//! this crate's code.
//!
//! Run: `cargo run --example gen_model > spec/tla/lib/RustObs.tla`
//! Checked by: `scripts/check-model.sh` (regenerate into a tempdir and diff).
//!
//! # What this is, and what it is not
//!
//! `Machine` below implements, in Rust, exactly the transition function
//! `Step`/`Closes` that `spec/tla/ExplorerReplay.tla` hard-codes. This program
//! runs the REAL `Explorer::explore` over it at each depth cap the model
//! sweeps, and emits the four report counters as TLA+ definitions. The model
//! computes those same four numbers ITSELF, from its own transitions, and
//! `ModelMatchesRust` compares them.
//!
//! That direction matters. Regeneration rewrites only the Rust side, so a
//! model that has drifted from `explore.rs` stays RED after regeneration — it
//! cannot heal into "somebody edited the number to match", which is exactly
//! what a golden vector does when the model is a hand-written re-implementation.
//!
//! It is not a proof that the model refines `explore.rs`. It binds four
//! scalars per cap in one world mode. What it buys is that a change to the
//! depth arm (`explore.rs:206-216`), to the narrowing at `:280`, to terminal
//! counting at `:249-262` or to the dedupe at `:264` moves a number here and
//! turns the model red — which is the failure the last one of these shipped
//! through.

use newtui::{Component, Explorer, Flow, Key, Row, View};

/// The five-node machine `ExplorerReplay.tla` models, as a real component.
///
/// `p0 -right-> p1 -right-> p2 -right-> p2`, and `esc` closes from anywhere
/// into `bye`. `w0` is the model's unreachable decoy start; it is never
/// entered from `p0` and so never appears in this walk.
struct Machine {
    node: &'static str,
}

impl Component for Machine {
    fn handle(&mut self, key: Key) -> Flow {
        match key {
            Key::Esc => {
                self.node = "bye";
                Flow::Close(false)
            }
            Key::Right => {
                self.node = match self.node {
                    "p0" => "p1",
                    "p1" => "p2",
                    other => other,
                };
                Flow::Stay
            }
            _ => Flow::Stay,
        }
    }

    fn view(&self) -> View {
        // The node is in the view, so the DEFAULT fingerprint (`of_view`) is
        // injective on nodes — which is what lets the model's `FpOf` be the
        // identity honestly rather than by assumption.
        View::titled("machine").row(Row::new("node", self.node))
    }
}

/// The depth caps the model sweeps. Must equal `DepthCaps` in every `.cfg`;
/// `ExplorerReplay.tla` carries `ASSUME DepthCaps \subseteq ObsCaps`.
const CAPS: [usize; 2] = [1, 3];

fn main() {
    let alphabet = [Key::Right, Key::Esc];
    let reports: Vec<_> = CAPS
        .iter()
        .map(|&cap| {
            // `max_states` is deliberately left at its default: the model does
            // not model that limit, so a run that hit it would be comparing
            // two different machines.
            Explorer::new(alphabet)
                .max_depth(cap)
                .explore(|| Machine { node: "p0" }, &[])
        })
        .collect();

    let caps = CAPS
        .iter()
        .map(usize::to_string)
        .collect::<Vec<_>>()
        .join(", ");

    let arm = |f: &dyn Fn(usize) -> String| {
        CAPS.iter()
            .enumerate()
            .map(|(i, cap)| format!("d = {cap} -> {}", f(i)))
            .collect::<Vec<_>>()
            .join(" [] ")
    };

    // `CASE` with no `OTHER`: an unmatched cap is a TLC error rather than a
    // silently plausible default.
    println!("---------------------------- MODULE RustObs ----------------------------");
    println!("\\* GENERATED by `cargo run --example gen_model` — DO NOT EDIT.");
    println!("\\*");
    println!("\\* Observed report counters from a REAL `Explorer::explore` run over the");
    println!("\\* component in `examples/gen_model.rs`, which implements exactly the");
    println!("\\* `Step`/`Closes` transition function `ExplorerReplay.tla` hard-codes.");
    println!("\\* `ModelMatchesRust` compares these against counters the model computes");
    println!("\\* for itself. Regenerate with `scripts/check-model.sh --write`; that");
    println!("\\* script also fails if the committed copy has drifted.");
    println!("EXTENDS Naturals");
    println!();
    println!("ObsCaps == {{{caps}}}");
    println!(
        "ObsStates      == [d \\in ObsCaps |-> CASE {}]",
        arm(&|i| reports[i].states.to_string())
    );
    println!(
        "ObsTransitions == [d \\in ObsCaps |-> CASE {}]",
        arm(&|i| reports[i].transitions.to_string())
    );
    println!(
        "ObsTerminal    == [d \\in ObsCaps |-> CASE {}]",
        arm(&|i| reports[i].terminal_states.to_string())
    );
    println!(
        "ObsExhausted   == [d \\in ObsCaps |-> CASE {}]",
        arm(&|i| String::from(if reports[i].exhausted {
            "TRUE"
        } else {
            "FALSE"
        }))
    );
    println!("=======================================================================");
}
