#!/usr/bin/env bash
# Record the real catalog host with fixed, checked-in fixtures and VHS tapes.
set -euo pipefail

cd "$(dirname "$0")/.."
repo_root="$PWD"
recorder="${VHS_BIN:-vhs}"
for dependency in cargo python3 "$recorder" ffmpeg; do
  command -v "$dependency" >/dev/null || {
    echo "catalog capture requires $dependency" >&2
    exit 1
  }
done

report="$(mktemp "${TMPDIR:-/tmp}/newtui-catalog-build.XXXXXX")"
capture_dir="$(mktemp -d "${TMPDIR:-/tmp}/newtui-catalog-capture.XXXXXX")"
trap 'rm -f "$report"; rm -rf "$capture_dir"' EXIT
cargo build --locked -p newtui-catalog --message-format=json >"$report"
# Cargo supplies the path, so CARGO_TARGET_DIR and platform suffixes work too.
NEWTUI_CATALOG_BIN="$(python3 - "$report" <<'PY'
import json
import sys

executables = []
with open(sys.argv[1], encoding="utf-8") as messages:
    for line in messages:
        message = json.loads(line)
        if (message.get("reason") == "compiler-artifact"
                and message.get("target", {}).get("name") == "newtui-catalog"
                and message.get("executable")):
            executables.append(message["executable"])
if len(executables) != 1:
    raise SystemExit("cargo did not report exactly one catalog executable")
print(executables[0])
PY
)"
export NEWTUI_CATALOG_BIN

# Stage the output separately: a recorder can exit successfully without writing
# a frame, and an older checked-in image must never disguise that failure.
mkdir -p "$capture_dir/docs/widgets/generated" "$capture_dir/demos/catalog"
(
  cd "$capture_dir"
  # The recording is a color terminal even when the calling automation uses
  # NO_COLOR/TERM=dumb for build logs. This affects only the capture process.
  unset NO_COLOR
  export TERM=xterm-256color COLORTERM=truecolor
  for tape in "$repo_root"/demos/catalog/*.tape; do
    "$recorder" "$tape"
  done
)
captures=(
  docs/widgets/generated/catalog.png
  docs/widgets/generated/butterfly.png
  docs/widgets/generated/heat-meter.png
  docs/widgets/generated/gauge.png
  docs/widgets/generated/catalog-light.png
  docs/widgets/generated/catalog-narrow.png
  docs/widgets/generated/catalog-error.png
  demos/catalog/catalog.gif
  demos/catalog/light.gif
  demos/catalog/narrow.gif
  demos/catalog/error.gif
)
for capture in "${captures[@]}"; do
  if [[ ! -s "$capture_dir/$capture" ]]; then
    echo "recorder did not create $capture; existing captures were preserved" >&2
    exit 1
  fi
done
ffmpeg -hide_banner -loglevel error -y -i "$capture_dir/demos/catalog/catalog.gif" \
  -plays 0 -f apng "$capture_dir/demos/catalog/catalog.png"
test -s "$capture_dir/demos/catalog/catalog.png"
captures+=(demos/catalog/catalog.png)
mkdir -p docs/widgets/generated
for capture in "${captures[@]}"; do
  cp "$capture_dir/$capture" "$capture"
done

# This is a reproduction record, not a new content identity or a hash scheme.
{
  echo '# Catalog captures'
  echo
  echo 'Generated by `just catalog-capture` from the real terminal host.'
  echo
  echo "Source revision: $(git rev-parse HEAD)"
  echo "Recorder: $("$recorder" --version)"
  if [[ -n "$(git status --porcelain -- .)" ]]; then
    echo 'Working tree: includes the reviewed changes accompanying these captures.'
  fi
  echo
  echo 'Fixtures, interaction sequences, palette, font and viewport dimensions:'
  for tape in demos/catalog/*.tape; do
    echo
    echo "## $tape"
    echo
    echo '```text'
    cat "$tape"
    echo '```'
  done
} >docs/widgets/generated/CAPTURES.md

echo 'Captured catalog PNGs in docs/widgets/generated and GIF/APNG in demos/catalog.'
